### PR TITLE
My 'fixes' were mistakes

### PR DESCRIPTION
**Pull request by mikegilchrist**
While I thought I checked my changes to ensure they worked, it turns out they only work if your init.el has already been evaluated (i.e. if you evaluate the init.el buffer within an emacs session that already tried to load it.).  If you start a new session, these changes lead to an error.

### CODE REVIEW

**Comment by manateelazycat** [comment]
Why this patch remove password type？

If remove password type, some input field won't work.

**Comment by mikegilchrist** [comment]
I'm still learning the ropes for git, but I don't believe I removed the password support.  I tried to revert back to that commit (ea6c0e2).

**Comment by MatthewZMD** [comment]
See files changed for your changes in this PR: https://github.com/emacs-eaf/emacs-application-framework/pull/1003/files

**Comment by mikegilchrist** [comment]
Okay.  My apologies.  I will try again...

**Pull request closed without merging**
