### PR TITLE
use base64.b64decode instead of decodestring

### PR DESCRIPTION
**Pull request by thyecust**
see #783 for details

### CODE REVIEW

**Comment by manateelazycat** [comment]
Can you give me a link for test your patch?

**Comment by thyecust** [comment]
I used a `eaf-image-processing` app for test

1. Add following info into `applications.json`
```json
"eaf-image-processing": {
  "name": "EAF Image Processing",
  "type": "app",
  "gitee": "https://gitee.com/thyecust/eaf-image-processing.git",
  "gitee_ssh": "git@gitee.com:thyecust/eaf-image-processing.git"
}
```
2. Run this command to install it
```bash
python3 ./install-eaf.py --ignore-core-deps --install-app eaf-image-processing --use-gitee 
```
3. Add this to `init.el`
```lisp
(require 'eaf-image-processing)
```
4. Run Emacs and call `M-x eaf-open-image-processing`, you can upload an image and click save. The image will save to your disk and Emacs show `Save image : [path of the image]`

**Comment by manateelazycat** [comment]
I have test it, great patch!

**Comment by thyecust** [comment]
Thansk @MatthewZMD

**Comment by MatthewZMD** [comment]
Great work!

**Pull request merged**
